name: Build Flutter APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.x'
      - run: |
          # إنشاء هيكل المشروع وترتيب الملفات
          flutter create . --overwrite --org houshab_data_android
          mkdir -p lib
          # نقل ملف الماين إذا كان خارج مجلد lib
          [ -f main.dart ] && mv main.dart lib/main.dart || true
          mkdir -p android/app
          # نقل ملف الجيسون للمكان الصحيح
          cp google-services.json android/app/google-services.json || true
          flutter pub get
          flutter build apk --release --no-tree-shake-icons
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
